### PR TITLE
npmrc

### PR DESCRIPTION
**Pull request by recursivefunk**
@jcarbaugh @josephabrahams gut check on this?

### CODE REVIEW

**Comment by jcarbaugh** [comment]
Looks good.

Overall though, some of the feedback from Andrew's use of this on mo-static indicated that the post_gen_project hook might not be the best place for project setup. It's only called once when the project is generated, but other people that clone the project won't have it run for them.

In mo-django I'm going to add a bin/bootstrap script that can be run to do the initial set up of the project.

**Comment by josephabrahams** [comment]
What happens if you have npmrc set to a non-existant key but no private repos are used?

**Comment by recursivefunk** [comment]
Craps out. If npm sees the file, it's wants the env set @josephabrahams regardless

**Comment by josephabrahams** [comment]
Right, but what if it's set but it but it's set to XXXXXXXX. Does it work?

**Comment by recursivefunk** [comment]
Yep. That's exactly what this PR is doing. Setting it to a dummy value in order to appease npm and continue with the install. Since there are no private modules, the fake value is fine because no actual checks are made. It feels hacky hence, the PR @josephabrahams

**Comment by josephabrahams** [comment]
Why not just set it in the .env file and run `npm install` with forego?

Joseph Abrahams | VP of Engineering
ISL https://isl.co/ | 256.302.0500
Twitter http://twitter.com/josephabrahams | LinkedIn https://www.linkedin.com/in/josephabrahams

**Comment by recursivefunk** [comment]
Eh, that might work. That's one more thing users have to have installed just to generate the project

**Comment by josephabrahams** [comment]
I guess I just don't like automating everything into a single action.

Feels very 'isl-cloud'.

Joseph Abrahams | VP of Engineering
ISL https://isl.co/ | 256.302.0500
Twitter http://twitter.com/josephabrahams | LinkedIn https://www.linkedin.com/in/josephabrahams

**Pull request merged**
